DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS
(
    -- ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

--CREATE
INSERT INTO TB_HEROIS
    (NOME,PODER)
VALUES('FLASH', 'VELOCIDADE'),
    ('HOMEM-ARANHA', 'TEIAS'),
    ('BATMAN', 'DINHEIRO')

--READ
SELECT *
FROM TB_HEROIS
SELECT *
FROM TB_HEROIS
WHERE NAME ='FLASH'

--UPDATE
UPDATE TB_HEROIS SET NOME='SUPERMAN', PODER='FORÇA' WHERE ID = 1

--DELETE
DELETE FROM TB_HEROIS WHERE ID = 2